import { DeviceEventEmitter, NativeModules, Platform } from 'react-native';
import NfcManager, { NfcAdapter, NfcTech } from 'react-native-nfc-manager';

// Custom AID registered in the HCE service (see plugins/withTomoHce.js, which
// generates android/app/src/main/res/xml/apduservice.xml on prebuild).
const AID = 'F0544F4D4F31';

type HceModule = {
  setPayload: (payload: string) => Promise<void>;
  clear: () => Promise<void>;
  lastTapAt: () => Promise<number>;
  // Added later than the other methods; may be missing on stale dev-client
  // binaries, so call sites treat it as optional.
  lastServedAt?: () => Promise<number>;
  getDiagnostics?: () => Promise<HceDiagnostics>;
};

// Self-contained native reader generated by plugins/withTomoHce.js. This is
// the primary scan mechanism: react-native-nfc-manager v3 documents itself as
// legacy-architecture-only, and on this app's RN 0.86 new-arch/bridgeless
// runtime its reader path can silently no-op (registerTagEvent resolves even
// when reader mode was never armed, and its deferred tag callback crosses the
// interop layer from an NFC binder thread). TomoReader talks straight to the
// Android SDK instead; nfc-manager remains only as a fallback for stale
// binaries that predate TomoReader.
type ReaderModule = {
  ping: () => Promise<string>;
  isSupported: () => Promise<boolean>;
  isEnabled: () => Promise<boolean>;
  getLog: () => Promise<string[]>;
  takeResult: () => Promise<string | null>;
  readOnce: (timeoutMs: number) => Promise<string>;
  stop: () => Promise<void>;
};

export type HceDiagnostics = {
  payloadSet: boolean;
  tappedAt: number;
  servedAt: number;
  apduCount: number;
  lastApduHex: string;
  lastRespHex: string;
  deactivatedAt: number;
  deactivatedReason: number;
};

const TomoHce: HceModule | undefined = NativeModules.TomoHce ?? undefined;
const TomoReader: ReaderModule | undefined = NativeModules.TomoReader ?? undefined;

// --- diagnostics bus ---------------------------------------------------------
//
// A small in-JS ring buffer that the hidden overlay on ConfirmScreen renders.
// JS-side steps are appended directly; native-side steps live in the Kotlin
// TomoDiag ring and are PULLED via TomoReader.getLog() on every snapshot, so
// the overlay stays truthful even if bridge event delivery is broken. The
// TomoNfcEvent device event is used only as a "something happened" tick to
// refresh the overlay quickly.

export type DiagEntry = { ts: number; msg: string; src: 'js' | 'native' | 'hce' };

const jsDiag: DiagEntry[] = [];
const diagListeners = new Set<() => void>();
let diagEventWired = false;

function notifyDiag(): void {
  for (const l of diagListeners) {
    try {
      l();
    } catch {
      // listeners must never break the feature
    }
  }
}

export function diagLog(msg: string): void {
  jsDiag.push({ ts: Date.now(), msg, src: 'js' });
  if (jsDiag.length > 300) jsDiag.splice(0, jsDiag.length - 300);
  notifyDiag();
}

export function subscribeDiag(cb: () => void): () => void {
  diagListeners.add(cb);
  if (!diagEventWired && Platform.OS === 'android') {
    diagEventWired = true;
    try {
      DeviceEventEmitter.addListener('TomoNfcEvent', () => notifyDiag());
    } catch {
      // pull path still works
    }
  }
  return () => {
    diagListeners.delete(cb);
  };
}

export function moduleInfo(): { tomoHce: boolean; tomoReader: boolean; nfcManagerNative: boolean } {
  return {
    tomoHce: !!TomoHce,
    tomoReader: !!TomoReader,
    nfcManagerNative: !!NativeModules.NfcManager,
  };
}

export async function hceDiagnostics(): Promise<HceDiagnostics | null> {
  try {
    return (await TomoHce?.getDiagnostics?.()) ?? null;
  } catch {
    return null;
  }
}

export async function getDiagSnapshot(): Promise<DiagEntry[]> {
  const out: DiagEntry[] = [...jsDiag];
  try {
    const native = (await TomoReader?.getLog()) ?? [];
    for (const line of native) {
      const sep = line.indexOf('|');
      if (sep <= 0) continue;
      const ts = Number(line.slice(0, sep));
      const msg = line.slice(sep + 1);
      out.push({ ts: Number.isFinite(ts) ? ts : 0, msg, src: msg.startsWith('hce:') ? 'hce' : 'native' });
    }
  } catch (e) {
    out.push({ ts: Date.now(), msg: `diag: getLog failed (${errMsg(e)})`, src: 'js' });
  }
  const hce = await hceDiagnostics();
  if (hce) {
    out.push({
      ts: Date.now(),
      msg:
        `hce-state: payload=${hce.payloadSet ? 'set' : 'none'} apdus=${hce.apduCount}` +
        ` tapped=${hce.tappedAt || '-'} served=${hce.servedAt || '-'}`,
      src: 'hce',
    });
  }
  out.sort((a, b) => a.ts - b.ts);
  return out.slice(-140);
}

function errMsg(e: unknown): string {
  if (e instanceof Error && e.message) return e.message;
  return String(e);
}

function errCode(e: unknown): string | undefined {
  if (e && typeof e === 'object' && 'code' in e && typeof (e as { code?: unknown }).code === 'string') {
    return (e as { code: string }).code;
  }
  return undefined;
}

// --- availability ------------------------------------------------------------

export function hceAvailable(): boolean {
  return Platform.OS === 'android' && !!TomoHce;
}

// supported = hardware exists; enabled = the NFC toggle is actually on.
// Answered natively by TomoReader (a plain NfcAdapter.getDefaultAdapter check,
// no activity or third-party state involved); falls back to nfc-manager only
// on binaries without TomoReader. Never throws.
let lastLoggedState = '';

export async function nfcState(): Promise<{ supported: boolean; enabled: boolean }> {
  let state = { supported: false, enabled: false };
  let via = 'none';
  if (Platform.OS === 'android') {
    if (TomoReader) {
      via = 'TomoReader';
      try {
        const [supported, enabled] = await Promise.all([
          TomoReader.isSupported(),
          TomoReader.isEnabled(),
        ]);
        state = { supported, enabled };
      } catch (e) {
        via = `TomoReader failed (${errMsg(e)})`;
      }
    } else {
      via = 'nfc-manager';
      try {
        const supported = await NfcManager.isSupported();
        const enabled = supported ? await NfcManager.isEnabled() : false;
        state = { supported, enabled };
      } catch (e) {
        via = `nfc-manager failed (${errMsg(e)})`;
      }
    }
  }
  const summary = `nfcState: supported=${state.supported} enabled=${state.enabled} via=${via}`;
  if (summary !== lastLoggedState) {
    lastLoggedState = summary;
    diagLog(summary);
  }
  return state;
}

export async function nfcAvailable(): Promise<boolean> {
  const s = await nfcState();
  return s.supported;
}

// Timestamp (ms) of the last time another phone touched ours while showing
// (any APDU reached our HCE service, even if we could not serve the payload).
export async function lastTapAt(): Promise<number> {
  try {
    return (await TomoHce?.lastTapAt()) ?? 0;
  } catch {
    return 0;
  }
}

// Timestamp (ms) of the last time the payload was actually delivered to a
// reader with SW 9000. lastTapAt > 0 but lastServedAt == 0 means radio contact
// happened but the SELECT never matched or no payload was set - that
// distinction pinpoints where a failing tap died.
export async function lastServedAt(): Promise<number> {
  try {
    return (await TomoHce?.lastServedAt?.()) ?? 0;
  } catch {
    return 0;
  }
}

// --- show side ---------------------------------------------------------------
//
// The QR code is always shown; NFC is a bonus transport. The payload is armed
// whenever the native module exists - deliberately NOT gated on the adapter
// state, so a wrong or failing state check can never silently disable HCE
// (arming costs nothing while the radio is off). The returned boolean only
// drives the "touch your phones" hint: true when tapping should genuinely
// work. Unknown state fails OPEN (hint shown).
export async function startShowing(payload: string): Promise<boolean> {
  if (!TomoHce) {
    diagLog('show: TomoHce module missing, QR only');
    return false;
  }
  try {
    await TomoHce.setPayload(payload);
    diagLog(`show: payload armed (${payload.length} chars)`);
  } catch (e) {
    diagLog(`show: setPayload failed (${errMsg(e)})`);
    return false;
  }
  try {
    const s = await nfcState();
    if (!s.supported) {
      diagLog('show: no NFC hardware, QR only');
      return false;
    }
    if (!s.enabled) {
      diagLog('show: NFC toggle is off, tap hint hidden');
      return false;
    }
  } catch {
    diagLog('show: state check failed, assuming tappable');
  }
  return true;
}

export async function stopShowing(): Promise<void> {
  await TomoHce?.clear();
}

// --- scan side ---------------------------------------------------------------
//
// Reading another phone's HCE card MUST use Android reader mode: while active,
// reader mode "disables any peer-to-peer and card-emulation modes of the NFC
// adapter on this device" (NfcAdapter#enableReaderMode). Without it the
// scanning phone keeps polling AND listening as a card at the same time - and
// since both phones run this app, both advertise the same Tomo AID, so the two
// controllers pair up in a random direction on every tap. Reader mode pins the
// roles: scanner = reader, shower = card.
//
// Primary path: TomoReader.readOnce() does everything natively (enableReaderMode
// on the main thread, IsoDep connect + SELECT transceive on the tag's binder
// thread) and resolves with the payload. On top of the returned promise there
// are two independent safety nets, because a deferred promise crossing the
// bridge is exactly the kind of plumbing this rewrite stopped trusting:
//  - a rescue poll: the native side also parks the payload in a slot that
//    TomoReader.takeResult() hands over via a fresh request/response call;
//  - a JS-side hard timeout slightly longer than the native one.

const NATIVE_READ_TIMEOUT_MS = 20000;
const HARD_TIMEOUT_MS = NATIVE_READ_TIMEOUT_MS + 4000;
const RESCUE_POLL_MS = 1200;

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

async function tomoScanOnce(reader: ReaderModule): Promise<string> {
  diagLog(`scan: TomoReader.readOnce(${NATIVE_READ_TIMEOUT_MS}ms)`);
  const native = reader.readOnce(NATIVE_READ_TIMEOUT_MS);
  native.catch(() => {}); // the race may abandon it; never leave an unhandled rejection
  let alive = true;
  const rescue = (async (): Promise<string> => {
    while (alive) {
      await sleep(RESCUE_POLL_MS);
      if (!alive) break;
      try {
        const r = await reader.takeResult();
        if (r != null) {
          diagLog('scan: payload arrived via rescue poll (bridge promise was late)');
          return r;
        }
      } catch {
        // keep polling
      }
    }
    // Losing arm of the race: park forever, the race has already settled.
    return new Promise<never>(() => {});
  })();
  const hardTimeout = (async (): Promise<never> => {
    await sleep(HARD_TIMEOUT_MS);
    throw new Error('hard-timeout');
  })();
  try {
    return await Promise.race([native, rescue, hardTimeout]);
  } catch (e) {
    // Prefer the structured code; fall back to message text in case the
    // bridge implementation drops the code property.
    const m = errMsg(e);
    let code = errCode(e);
    if (!code) {
      if (m.includes('No phone was read in time')) code = 'timeout';
      else if (m.includes('Scan was cancelled')) code = 'cancelled';
    }
    if (code === 'timeout') throw new Error('still waiting for a touch');
    if (code === 'cancelled') throw new Error('cancelled');
    if (code === 'no_nfc') throw new Error('This phone has no NFC');
    if (code === 'nfc_off') throw new Error('NFC is turned off in your phone settings');
    if (code === 'no_activity') throw new Error('bring the app to the foreground');
    if (code === 'busy') {
      await reader.stop().catch(() => {});
      throw new Error('restarting the reader');
    }
    if (m === 'hard-timeout') {
      diagLog('scan: JS hard timeout - native readOnce never settled, forcing stop()');
      await reader.stop().catch(() => {});
      throw new Error('still waiting for a touch');
    }
    throw e instanceof Error ? e : new Error(errMsg(e));
  } finally {
    alive = false;
  }
}

// --- legacy nfc-manager path (only for binaries without TomoReader) ----------

const READER_MODE_OPTIONS = {
  isReaderModeEnabled: true,
  readerModeFlags:
    NfcAdapter.FLAG_READER_NFC_A |
    NfcAdapter.FLAG_READER_NFC_B |
    NfcAdapter.FLAG_READER_SKIP_NDEF_CHECK,
};

let legacySessionOpen = false;

async function legacyScanOnce(): Promise<string> {
  diagLog('scan: TomoReader missing, falling back to nfc-manager reader mode');
  await NfcManager.start();
  if (!legacySessionOpen) {
    await NfcManager.registerTagEvent(READER_MODE_OPTIONS);
    legacySessionOpen = true;
    diagLog('scan: nfc-manager session registered');
  }
  try {
    const tech = await NfcManager.requestTechnology(NfcTech.IsoDep);
    if (tech !== NfcTech.IsoDep) {
      throw new Error('the touch was too quick');
    }
    const select = [0x00, 0xa4, 0x04, 0x00, AID.length / 2, ...toBytes(AID), 0x00];
    diagLog(`scan: (legacy) apdu >> ${toHex(select)}`);
    const resp: number[] = await NfcManager.isoDepHandler.transceive(select);
    diagLog(`scan: (legacy) apdu << ${toHex(resp)}`);
    if (resp.length < 2) throw new Error('Empty response');
    const sw = (resp[resp.length - 2] << 8) | resp[resp.length - 1];
    if (sw !== 0x9000) throw new Error('The other phone is not showing a code right now');
    const data = resp.slice(0, -2);
    return String.fromCharCode(...data);
  } finally {
    await NfcManager.cancelTechnologyRequest().catch(() => {});
  }
}

function toBytes(hex: string): number[] {
  const out: number[] = [];
  for (let i = 0; i < hex.length; i += 2) out.push(parseInt(hex.slice(i, i + 2), 16));
  return out;
}

function toHex(bytes: number[]): string {
  return bytes.map((b) => (b & 0xff).toString(16).padStart(2, '0').toUpperCase()).join('');
}

// "Scan" side: read the other phone once over NFC. Resolves with its payload
// string; rejects (with a human-readable message) when nothing was read.
export async function scanOnce(): Promise<string> {
  if (TomoReader) {
    const p = await tomoScanOnce(TomoReader);
    diagLog(`scan: payload received (${p.length} chars, "${p.slice(0, 12)}...")`);
    return p;
  }
  return legacyScanOnce();
}

export async function cancelScan(): Promise<void> {
  diagLog('scan: cancel');
  await TomoReader?.stop().catch(() => {});
  if (legacySessionOpen) {
    legacySessionOpen = false;
    await NfcManager.cancelTechnologyRequest().catch(() => {});
    await NfcManager.unregisterTagEvent().catch(() => {});
  }
}
